### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by NekoTony** [tsurumeso/waifu2x-chainer#1]
Level 3 denoising... Traceback (most recent call last):
  File "waifu2x.py", line 133, in <module>
    dst = denoise_image(dst, models['noise'], args)
  File "waifu2x.py", line 21, in denoise_image
    dst = reconstruct.image(src, model, cfg.block_size, cfg.batch_size)
  File "/home/lib/reconstruct.py", line 137, in image
    dst = blockwise(src, model, block_size, batch_size)
  File "/home/lib/reconstruct.py", line 53, in blockwise
    batch_y = model(batch_x)
  File "/home/lib/srcnn.py", line 26, in __call__
    h = F.leaky_relu(self.conv3(h), 0.1)
  File "/usr/local/lib/python3.5/dist-packages/chainer/links/connection/convolution_2d.py", line 154, in __call__
    x, self.W, self.b, self.stride, self.pad)
  File "/usr/local/lib/python3.5/dist-packages/chainer/functions/connection/convolution_2d.py", line 439, in convolution_2d
    return func(x, W, b)
  File "/usr/local/lib/python3.5/dist-packages/chainer/function.py", line 200, in __call__
    outputs = self.forward(in_data)
  File "/usr/local/lib/python3.5/dist-packages/chainer/function.py", line 329, in forward
    return self.forward_cpu(inputs)
  File "/usr/local/lib/python3.5/dist-packages/chainer/functions/connection/convolution_2d.py", line 87, in forward_cpu
    cover_all=self.cover_all)
  File "/usr/local/lib/python3.5/dist-packages/chainer/utils/conv.py", line 33, in im2col_cpu
    col = numpy.ndarray((n, c, kh, kw, out_h, out_w), dtype=img.dtype)
MemoryError

**Comment by tsurumeso** [comment]
MemoryError occurs when there is not enough memory. 
So you should reduce `--block_size` or `--batch_size` to set optional argument.
Maybe setting these values to half of default (`--block_size 32` or `--batch_size 4`) will not cause MemoryError.

**Comment by NekoTony** [comment]
lib not a module...

**Comment by tsurumeso** [comment]
What do you mean...? Please give me the details.

**Comment by NekoTony** [comment]
Import error lib not found

**Comment by tsurumeso** [comment]
Looking at your first comment seems to be successful to import lib.
I can't understand the issue, but It may be better to reinstall waifu2x-chainer.
