### ISSUE TITLE
RuntimeError: CUDA environment is not correctly set up

### ISSUE THREAD

**Issue by StrattonPau** [tsurumeso/waifu2x-chainer#27]
I have macOS and when I execute :

python3 waifu2x.py --method noise --noise_level 1 --input imgsd2.jpg  --arch VGG7 --gpu 0

I have this error:

Traceback (most recent call last):
  File "waifu2x.py", line 160, in <module>
    models = load_models(args)
  File "waifu2x.py", line 120, in load_models
    chainer.backends.cuda.check_cuda_available()
  File "/Users/pauperales/anaconda3/lib/python3.7/site-packages/chainer/backends/cuda.py", line 93, in check_cuda_available
    raise RuntimeError(msg)
RuntimeError: CUDA environment is not correctly set up
(see https://github.com/chainer/chainer#installation).cannot import name 'cuda' from 'cupy' (unknown location)

**Comment by edurenye** [comment]
Probably you have CUDA 11.1, it's not supported until this is fixed: https://github.com/chainer/chainer/pull/8583
And the dependency updated here afterwards.
