### ISSUE TITLE
--model_dirオプション使用時の挙動

### ISSUE THREAD

**Issue by f11894** [tsurumeso/waifu2x-chainer#5]
連日申し訳ありません。
--model_dirでRGBモデル以外のディレクトリを指定すると以下のようなエラーが出ます。
作業フォルダはC:\Users\***\Desktop\動作テストです。

python "C:\Users\***\waifu2x-chainer\waifu2x.py" -i "C:\Users\***\Desktop\動作テスト\001.png"  -m scale -s 2    -d "C:\Users\***\waifu2x-chainer\models\resnet10" -l 64  

Traceback (most recent call last):
  File "C:\Users\***\waifu2x-chainer\waifu2x.py", line 159, in <module>
    models = load_models(args)
  File "C:\Users\***\waifu2x-chainer\waifu2x.py", line 108, in load_models
    chainer.serializers.load_npz(model_path, models['scale'])
  File "C:\Users\***\Anaconda3\lib\site-packages\chainer\serializers\npz.py", line 153, in load_npz
    d.load(obj)
  File "C:\Users\***\Anaconda3\lib\site-packages\chainer\serializer.py", line 83, in load
    obj.serialize(self)
  File "C:\Users\***\Anaconda3\lib\site-packages\chainer\link.py", line 795, in serialize
    d[name].serialize(serializer[name])
  File "C:\Users\***\Anaconda3\lib\site-packages\chainer\link.py", line 551, in serialize
    data = serializer(name, param.data)
  File "C:\Users\***\Anaconda3\lib\site-packages\chainer\serializers\npz.py", line 116, in __call__
    dataset = self.npz[key]
  File "C:\Users\***\Anaconda3\lib\site-packages\numpy\lib\npyio.py", line 237, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'conv4/b is not a file in the archive'

また--model_dirと--archを同時に指定した場合は変換自体は成功しているようなのですが指定モデルの種類に関わらず出力ファイル名が全てmodel_rgbになってしまいます。

**Comment by tsurumeso** [comment]
--model_dir を指定した場合， --arch も指定しなければならない仕様となっています．出力ファイル名については改善します．

**Comment by f11894** [comment]
了解しました。

> --model_dir を指定した場合，--arch も指定しなければならない仕様となっています
これはどういう風に指定するのが正解か分からなかったので教えていただいて助かりました。
