### ISSUE TITLE
ResNet10を使って訓練する途中エラー発生

### ISSUE THREAD

**Issue by kenin0726** [tsurumeso/waifu2x-chainer#6]
エラーが発生したコード

``C:\Users\Kenin\waifu2x-chainer>python train.py --dataset_dir (dir) --method noise_scale --noise_level 1 --finetune test.npz --arch 2``

結果

```
* loading filelist... done
* loading model... done
* starting processes of dataset sampler... done
### epoch: 0 ###
  # inner epoch: 0
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\Kenin\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\Kenin\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Kenin\waifu2x-chainer\lib\dataset_sampler.py", line 85, in _worker
    xc_batch, yc_batch = pairwise_transform(img, cfg)
  File "C:\Users\Kenin\waifu2x-chainer\lib\pairwise_transform.py", line 151, in pairwise_transform
    raise ValueError('inner_scale must be > 1')
ValueError: inner_scale must be > 1
Process Process-2:
Traceback (most recent call last):
  File "C:\Users\Kenin\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\Kenin\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Kenin\waifu2x-chainer\lib\dataset_sampler.py", line 85, in _worker
    xc_batch, yc_batch = pairwise_transform(img, cfg)
  File "C:\Users\Kenin\waifu2x-chainer\lib\pairwise_transform.py", line 151, in pairwise_transform
    raise ValueError('inner_scale must be > 1')
ValueError: inner_scale must be > 1
```

`--method noise_scale`じゃなく`--method noise`を使用すると、エラーが発生しませんでした。

**Comment by tsurumeso** [comment]
VGG7モデルとResNet10モデルはニアレストネイバー法で二倍に拡大した画像を入力して高画質化を行います．一方でUpConv7モデルはモデル内部で拡大処理も行います．ノイズ除去と拡大を同時に行うモデルは後者のようなモデルでしかサポートしていません．したがって，ResNet10モデルを学習する場合はノイズ除去モデルと拡大モデルを別々に学習する必要があります．

**Comment by kenin0726** [comment]
あー！これはもしかして、仕様でしょうか？
それならば、appendixのbatファイルで説明が必要ではないかと思います。
コメントありがとうございます。

**Comment by tsurumeso** [comment]
考えておきます。
